# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-22 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StyleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('desc', models.CharField(max_length=1000, null=True)),
                ('ipath', models.CharField(max_length=200, null=True)),
                ('mpath', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
